service: recapify-telegram-cs-bot

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-2
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            - lambda:InvokeFunction
          Resource: '*'
  environment:
    TELEGRAM_BOT_TOKEN: ${env:TELEGRAM_BOT_TOKEN}
    SUPPORT_CHAT_ID: ${env:SUPPORT_CHAT_ID}
  apiGateway:
    minimumCompressionSize: 1024 # 압축 설정으로 비용 절감
    shouldStartNameWithService: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  webhook:
    handler: src/handler.webhook
    events:
      - http:
          path: webhook
          method: post
