service: recapify-telegram-cs-bot

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-2
  stage: prod
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            - lambda:InvokeFunction
          Resource: '*'
  environment:
    TELEGRAM_BOT_TOKEN: ${env:TELEGRAM_BOT_TOKEN}
    SUPPORT_CHAT_ID: ${env:SUPPORT_CHAT_ID}
  apiGateway:
    minimumCompressionSize: 1024 # 압축 설정으로 비용 절감
    shouldStartNameWithService: true
    apiKeys: []
    domain:
      domainName: recapify-telegram.secretjuju.kr
      basePath: ''
      stage: ${self:provider.stage}
      createRoute53Record: true
      endpointType: 'regional'
      securityPolicy: tls_1_2
      certificateArn: ${env:CERTIFICATE_ARN}

plugins:
  - serverless-esbuild
  - serverless-offline

package:
  individually: true
  patterns:
    - '!node_modules/**'
    - '!.git/**'
    - '!.github/**'
    - '!.vscode/**'
    - '!test/**'
    - '!README.md'
    - '!.gitignore'
    - '!.prettierrc'
    - '!.eslintrc.json'
    - '!tsconfig.json'

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    exclude: ['aws-sdk']
    target: 'node18'
    platform: 'node'
    concurrency: 10

functions:
  webhook:
    handler: src/handler.webhook
    events:
      - http:
          path: webhook
          method: post
